### ISSUE TITLE
Setup paypal Integration

### ISSUE THREAD

**Issue by PrototypeAlex** [JavaScript-NZ/legacy.javascript.org.nz#1]
I was thinking we could just use this flow, minus the 'subscribe' button: 

https://developer.paypal.com/docs/classic/paypal-payments-standard/integration-guide/subscribe_buttons/

Happy to do it when I've got some time, will try aim to give it a go in the weekend.

**Comment by Unfocused** [comment]
The Kaching API makes this quite a bit nicer to deal with, IMO:
https://www.npmjs.org/package/kaching-paypal
And would let us easily add/use other payment methods in the future.

**Comment by PrototypeAlex** [comment]
I'm new to integrating paypal, so any recommendation is good. 

Does katching support subscription setup?

**Comment by Unfocused** [comment]
It uses the Paypal REST SDK, which supports it. But I don't know if kaching-paypal supports it directly or not.

But, we need a specially approved Paypal account to be able to do subscriptions. So I was assuming we'd just do one-off payments anyway, since that's easier.

**Comment by veb** [comment]
I have done quite a bit of work with PayPal subscriptions before. Not in
the least hard, but you really need to be careful what gets passed to the
backend from the client. (Ever heard of people changing the pricing of
something to $0.01 because the developer relied on the API too much...?)

Sounds fun.

On Mon, Nov 3, 2014 at 9:56 PM, Blair McBride notifications@github.com
wrote:

> It uses the Paypal REST SDK, which supports it. But I don't know if
> kaching-paypal supports it directly or not.
> 
> But, we need a specially approved Paypal account to be able to do
> subscriptions. So I was assuming we'd just do one-off payments anyway,
> since that's easier.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/JavaScript-NZ/javascript.org.nz/issues/1#issuecomment-61451972
> .

## 

Mike Mackenzie, _BInfoTech_
Manager and Software Developer at veb

http://veb.co.nz
Dunedin, New Zealand
